### ISSUE TITLE
geomtextpath fails CRAN check

### ISSUE THREAD

**Issue by friendly** [AllanCameron/geomtextpath#118] opened 2024-06-03 14:27 UTC
I use `geomtextpath` for vignette examples in my `nestedLogit` package.  I just got an email from CRAN that my package fails to check:

```
 Quitting from lines 150-156 [wlf-ggplot-p2] (plotting-ggplot.Rmd)
  Error: processing vignette 'plotting-ggplot.Rmd' failed with diagnostics:
  Problem while converting geom to grob.
  ℹ Error occurred in the 4th layer.
  Caused by error in `txt$shape[, shape_vars]`:
  ! Can't subset columns that don't exist.
  ✖ Column `x_midpoint` doesn't exist.
```

But I see that `geomtextpath` also fails for essentially the same problems: See the results at https://cloud.r-project.org/web/checks/check_results_geomtextpath.html

Can you let me know your plans to resolve this?

**Comment by teunbrand** [comment] 2024-06-03 14:39
@AllanCameron #117 should have fixed this issue and geomtextpath should in theory be ready to send a hotfix to CRAN

**Comment by friendly** [comment] 2024-06-03 15:01
I installed the devel version from GitHub, and my examples now work.

**Comment by yutannihilation** [comment] 2024-06-10 23:43
Any chance to release the new version on CRAN? My package will be removed in a week. I'm wondering if I should remove the dependency on geomtextpath.

(for some reason, the deadline of my package is a week earlier than that of geomtextpath...)

https://cran.r-project.org/package=gghighlight
https://cran.r-project.org/package=geomtextpath

**Comment by AllanCameron** [comment] 2024-06-11 13:38
Sorry, I have been extremely tied up yesterday. I hope to get the updated version over to CRAN tomorrow.

**Comment by teunbrand** [comment] 2024-06-11 13:50
Allan if you're busy I'll offer to do the checklist, so you just have to accept the email when submitted to CRAN

**Comment by AllanCameron** [comment] 2024-06-11 13:54
If you have time that would be great Teun.

**Comment by bbolker** [comment] 2024-06-12 15:33
Just hit this myself, thought it was a `textshaping` bug (this error occurs with `textshaping` version 0.4 but not 0.3.7). Thanks for saving the trouble and confusion of posting a bug report for `textshaping` ...

**Comment by friendly** [comment] 2024-06-13 00:27
Reminder: My package `nestedLogit` and `gghighlight` both of which `Suggests: geomtextpath` are due to be removed from CRAN on 6/17/2024,  **FIVE DAYS** from now.

Once a package is removed, it is treated as NEW by CRAN checks, which entails much more rigorous testing and is a real pain in the butt.

Unknown to me is how long before the removal date for `nestedLogit` your revised package that fixes this error must be accepted on CRAN.

Can you please advise me of your plans for `geomtextpath`?

The only thing I can do is to remove or revise the vignette in which I use `geomtextpath`, which I'd rather avoid.

**Comment by yutannihilation** [comment] 2024-06-13 00:45
@friendly 
Did you already inform CRAN that the failure is due to the incompatibility between textshaping and geomtextpath? I already emailed them and they confirmed. If my package will be archived before geomtextpath, it would be CRAN's fault.

**Comment by AllanCameron** [comment] 2024-06-13 06:44
@yutannihilation @friendly @bbolker I have already submitted the revised version, and this morning I have had a confirmatory e-mail that it is on its way to CRAN. I apologise for the delay in sorting this out.

**Comment by yutannihilation** [comment] 2024-06-13 08:36
Great! Thanks for maintaining this wonderful package.

**Comment by teunbrand** [comment] 2024-12-10 15:44
CRAN checks are fine now, so I'll close this issue

**Closed by teunbrand** 2024-12-10 15:44 UTC
