### ISSUE TITLE
Chinese character support

### ISSUE THREAD

**Issue by AllanCameron** [AllanCameron/geomtextpath#73] opened 2022-02-23 10:52 UTC
I am considering [this SO question](https://stackoverflow.com/questions/71231603/in-r-geomtextpath-does-its-not-support-chinese) as a feature request. I have no idea how feasible or practical this is, but it seems reasonable to explore it.

The following demonstrates the issue (it doesn't work via reprex due to limited unicode support)

``` r
library(tidyverse)
library(geomtextpath)
plot_data_2 <- data.frame(category=c('品类A','品类B','品类C','品类D'),
                          amount=c(1,6,4,7))

plot_data_2 %>% ggplot(aes(x=1,y=amount,fill=category))+
  geom_col()+geom_textpath(position = position_stack(vjust=0.5),
                           aes(label=category))+
  coord_polar()
```
![image](https://user-images.githubusercontent.com/33987720/155304900-e44ae4e2-ac87-4f78-ba4a-9e8e1abd28df.png)

**Comment by teunbrand** [comment] 2022-02-23 21:53
We do already support Chinese character, whether it is simplified or traditional.  If you set the family to a font that does have glyphs for these, it works perfectly fine. 

``` r
library(tidyverse)
library(geomtextpath)
plot_data_2 <- data.frame(category=c('品类A','品类B','品类C','品类D'),
                          amount=c(1,6,4,7))

plot_data_2 %>% ggplot(aes(x=1,y=amount,fill=category))+
  geom_col()+geom_textpath(position = position_stack(vjust=0.5),
                           aes(label=category),
                           family = "Noto Sans TC")+
  coord_polar() +
  theme(legend.text = element_text(family = "Noto Sans TC"))
```


The issue is that the default font doesn't include glyphs for Chinese characters, which makes our 'convert font index back to glyph' step not work as intended. While it solves a lot of other issues for us, this step makes font fallback impossible (which is what graphics devices, including {ragg}, do behind the scenes). I've submitted a [feature request](https://github.com/r-lib/textshaping/issues/28) a while back to return glyphs as-is, so that we don't need the conversion step and thus font fallback would work.

**Comment by AllanCameron** [comment] 2022-02-23 22:29
Ah! I didn't have time to look at this in any detail earlier. I know from my work in parsing pdfs that vertical writing is sometimes used in CJK scripts, which presumably we can't realistically support, but it's good to know that there isn't anything we are doing to inherently suppress the glyphs.

Since we have our own fallback font mechanism now (including a freeware font) I wonder if we should think about using a maximally inclusive fallback font that contains these glyphs and a mechanism for using them where necessary.

**Comment by teunbrand** [comment] 2022-02-23 23:22
>  which presumably we can't realistically support,

I'm not exactly sure what the expectation would be for vertical text, as I don't think I've used it other than playing around with WordArt in the 90s. Would it be to place text on a straight line orthogonal to the curve? Or would it be a 90° rotation per-letter? I think that you can make a case for the text orthogonal to the curve. For example in the usecase of [this](https://twitter.com/_christiantesta/status/1486742008488206337?s=20&t=az6hVKR0L3Gmk38U5-Lyzw) type of plot, it would be nice if one could label the year orthogonally.

> I wonder if we should think about using a maximally inclusive fallback font

I think there is a technical limitation to fonts that makes it such that a font can't contain all unicode glyphs (discussion [here](https://stackoverflow.com/questions/34732718/why-isnt-there-a-font-that-contains-all-unicode-glyphs)). We could try to use `systemfonts::font_fallback()`, but I'm not sure how much overhead this adds, especially since it would need to be called for every substring. E.g. `systemfonts::font_fallback(unlist(strsplit('品类A', "")))`.

**Comment by teunbrand** [comment] 2024-12-10 19:00
I think we have sufficient support for non-latin scripts, but people just need to select a font with the right glyphs. For this reason, I'm going to close this issue.

**Closed by teunbrand** 2024-12-10 19:00 UTC
